//
// Generated file, do not edit! Created by opp_msgtool 6.0 from src/rtps/messages/sample.msg.
//

#ifndef __SAMPLE_M_H
#define __SAMPLE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace omnetpp {


}  // namespace omnetpp

#endif // ifndef __SAMPLE_M_H

